@startuml register-vaccination

Participant "External Entity"  as ExternalEntity
Participant "FHIR Facade"  as FHIRFacade
Participant "GIIS"  as GIIS

ExternalEntity -> FHIRFacade: POST Immunization (With each reference(Patient, Organization...)) 
FHIRFacade -> FHIRFacade: Data transformation for the API 
FHIRFacade -> GIIS: POST <endpoint>/{immunization_data}
GIIS --> FHIRFacade: Success
FHIRFacade --> ExternalEntity: {201 Status Code}

@enduml