@startuml search-vaccination

Participant "External Entity"  as ExternalEntity
Participant "FHIR Facade"  as FHIRFacade
Participant "GIIS"  as GIIS

ExternalEntity -> FHIRFacade: GET Patient (patient.identifier:<<value>>)
FHIRFacade -> GIIS: Query SELECT
GIIS --> FHIRFacade: Query result
FHIRFacade --> ExternalEntity: Bundle 0..* (Immunization)

@enduml