id: fhir.giis
canonical: https://paho.org/fhir/giis
name: giisIG
title: GIIS Implementation Guide
description: Implementation Guide for GIIS
status: draft # draft | active | retired | unknown
version: 0.1.5
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2023+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
publisher:
  name: CENS
  url: https://www.cens.cl

menu:
  Home: index.html
  Context: 
    "Objectives": objectives.html
    "Use cases": use_cases.html
    "Actors": actors.html
  Data model & Exchange: 
    "Transactions": transaction.html
    "Workflow": workflow.html
    "Data Dictionary": dictionary.html
    "Self generated Value Sets": auto_generated_VS.html
  Deployments: 
    "SMART Security": smart.html
    "References": ig_references.html
  Artifacts: artifacts.html
  # Testing: 
  #   "Postman collection": postman_collection.html
  #   "Test server": test_server.html
  Changes: changes.html

pages: 
  index.md:
  objectives.md:
  use_cases.md:
  actors.md:
  transaction.md:
  workflow.md:
  dictionary.md:
  auto_generated_VS.md:
  smart.md:
  ig_references.md:
  artifacts.html:
  changes.md:
  context.md:
  data_model_and_exchange.md:
  deployments.md: 

instanceOptions:
  # When set to true, slices must be referred to by name and not only by a numeric index in order to be used
  # in an Instance's assignment rule. All slices appear in the order in which they are specified in FSH rules.
  # While SUSHI defaults to false for legacy reasons, manualSliceOrding is recommended for new projects.
  manualSliceOrdering: true 