id: fhir.giis
canonical: http://example.org
name: giisIG
title: GIIS Implementation Guide
description: Implementation Guide for GIIS
status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2023+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
publisher:
  name: CENS
  url: www.cens.cl

menu:
  Home: index.html
  Context: 
    "Scope" : scope.html
    "Objectives": objectives.html
    "Use cases": usecases.html
  Data model & Exchange: 
    "Actors": actors.html
    "Transactions": transaction.html
    "Workflow": workflow.html
    "Data Dictionary": dictionary.html
    "Self generated Value Sets": autovs.html
  Deployments: 
    "SMART Security": smart.html
    "References": references.html
  Artifacts: artifacts.html
  Profiles: 
    "GIIS Patient": StructureDefinition-GIISPatient.html
    "Child Caretaker": StructureDefinition-ChildCaretaker.html
    "Health Facility": StructureDefinition-HealthFacility.html
    "Village": StructureDefinition-Village.html
  Testing: 
    "Postman collection": postmancoll.html
    "Test server": testserver.html

instanceOptions:
  # When set to true, slices must be referred to by name and not only by a numeric index in order to be used
  # in an Instance's assignment rule. All slices appear in the order in which they are specified in FSH rules.
  # While SUSHI defaults to false for legacy reasons, manualSliceOrding is recommended for new projects.
  manualSliceOrdering: true 