id: fhir.giis
canonical: https://paho.org/fhir/giis
name: giisIG
title: GIIS Implementation Guide
description: Implementation Guide for GIIS
status: draft # draft | active | retired | unknown
version: 0.1.8
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2023+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
publisher:
  name: CENS
  url: https://www.cens.cl

menu:
  Home: index.html
  Context: 
    "Objectives": objectives.html
    "Use cases": use_cases.html
  Data model & Exchange: 
    "Transactions": transaction.html
    "Workflow": workflow.html
    "Data Dictionary": dictionary.html
    "Inner generated Value Sets": inner_generated_VS.html
  Deployments: 
    "SMART Security": smart.html
    "References": ig_references.html
  Artifacts: artifacts.html
  See Also: 
    "Patient's request/response example": patient_request_response.html
    "Vaccination event's request/response example": ve_request_response.html
    "ESAVI's request/response example": esavi_request_response.html
pages: 
  index.md:
  objectives.md:
  use_cases.md:
  transaction.md:
  workflow.md:
  dictionary.md:
  inner_generated_VS.md:
  smart.md:
  ig_references.md:
  artifacts.html:
  patient_request_response.md:
  ve_request_response.md: 
  esavi_request_response.md:
  context.md:
  data_model_and_exchange.md:
  deployments.md: 

instanceOptions:
  # When set to true, slices must be referred to by name and not only by a numeric index in order to be used
  # in an Instance's assignment rule. All slices appear in the order in which they are specified in FSH rules.
  # While SUSHI defaults to false for legacy reasons, manualSliceOrding is recommended for new projects.
  manualSliceOrdering: true 